### ISSUE TITLE
Menunggu Update Terbaru

### ISSUE THREAD

**Issue by Meowfficer** [lakuapik/vscode-waktusholat#12]
Bang tidak update terbaru kah?, ekstensi ini sangat membantu saya untuk mengingat sholat
dan mohon tambahkan fitur suara adzan pada windows

terima kasih

**Comment by lakuapik** [comment]
sudah lama tidak ku update. nanti kalau ada waktu luang akan ku coba update lagi. btw, terima kasih masukannya. cheers 🍻

**Comment by Meowfficer** [comment]
> sudah lama tidak ku update. nanti kalau ada waktu luang akan ku coba update lagi. btw, terima kasih masukannya. cheers 🍻

Saya tunggu updatenya bang, semoga ada luang, semangat bang!

**Comment by lakuapik** [comment]
kabar baik @Meowfficer

barusan [rilis versi 2.0.0](https://github.com/lakuapik/vscode-waktusholat/releases/tag/v2.0.0) :rocket: 

silahkan perbarui ekstensimu!

untuk tutorial di windows mainkan suara adzan menyusul ya :smiley_cat:  
maklum saya sendiri gak pakai windows, nanti tak coba pinjem laptop teman dulu :joy_cat:

**Comment by Meowfficer** [comment]
> kabar baik @Meowfficer
> 
> barusan [rilis versi 2.0.0](https://github.com/lakuapik/vscode-waktusholat/releases/tag/v2.0.0) 🚀
> 
> silahkan perbarui ekstensimu!
> 
> untuk tutorial di windows mainkan suara adzan menyusul ya 😺
> maklum saya sendiri gak pakai windows, nanti tak coba pinjem laptop teman dulu 😹

Terima kasih atas update terbarunya, karena saya sangat menantikannya, alhamdulillah jadi inget sholat pas ngoding, semoga mas apik diberi kelancaran dalam pekerjaannya
