### ISSUE TITLE
Bug Pada Versi Terbaru

### ISSUE THREAD

**Issue by Meowfficer** [lakuapik/vscode-waktusholat#13]
Ekstensi tidak aktif pada versi terbaru, tidak muncul notifikasi ekstensi aktif atau lainnya

**Comment by lakuapik** [comment]
aku coba install uninstall bisa jalan kok ektensinya.

bisa lebih diperjelas lagi untuk masalahnya? @Meowfficer

**Comment by Meowfficer** [comment]
![image](https://user-images.githubusercontent.com/80162015/133714077-77c57077-e5e6-4d97-8fe1-5ecd920f6c8b.png)

**Comment by lakuapik** [comment]
@Meowfficer good news, di windows sekarang sudah bisa!

kontribusi dari @Notdet3cted  di #15.
