### ISSUE TITLE
Extension tidak muncul pada windows

### ISSUE THREAD

**Issue by Notdet3cted** [lakuapik/vscode-waktusholat#14]
Saya mencoba install extension pada windows akan tetapi status bar tidak muncul, saya mencoba clone repo dan run dev mode kemudian menemukan ini 
![vscode laku apik err](https://user-images.githubusercontent.com/37031932/209265071-271a6db1-3cec-4ad2-a387-ade79e4728d4.png)

saya rasa kesalahan ada pada line 267   **if (!existsSync(path)) mkdirSync(path);**

**Comment by lakuapik** [comment]
@Notdet3cted wah terima kasih banyak informasinya!

bisakah kamu buat PR untuk fix ini? saya sendiri tidak pakai windows, jadi belum bisa testing.

**Comment by lakuapik** [comment]
solved di #15
